
#include <emscripten/bind.h>

#include "libcellml/issue.h"

using namespace emscripten;


EMSCRIPTEN_BINDINGS(libcellml_issue) {

    enum_<libcellml::Issue::Cause>("Issue_Cause")
        .value("COMPONENT", libcellml::Issue::Cause::COMPONENT)
        .value("CONNECTION", libcellml::Issue::Cause::CONNECTION)
        .value("ENCAPSULATION", libcellml::Issue::Cause::ENCAPSULATION)
        .value("IMPORT", libcellml::Issue::Cause::IMPORT)
        .value("MATHML", libcellml::Issue::Cause::MATHML)
        .value("MODEL", libcellml::Issue::Cause::MODEL)
        .value("RESET", libcellml::Issue::Cause::RESET)
        .value("UNDEFINED", libcellml::Issue::Cause::UNDEFINED)
        .value("UNITS", libcellml::Issue::Cause::UNITS)
        .value("VARIABLE", libcellml::Issue::Cause::VARIABLE)
        .value("XML", libcellml::Issue::Cause::XML)
        .value("GENERATOR", libcellml::Issue::Cause::GENERATOR)
    ;

    enum_<libcellml::Issue::Level>("Issue_Level")
        .value("ERROR", libcellml::Issue::Level::ERROR)
        .value("WARNING", libcellml::Issue::Level::WARNING)
        .value("HINT", libcellml::Issue::Level::HINT)
    ;

    enum_<libcellml::Issue::ReferenceRule>("Issue_ReferenceRule")
        .value("UNDEFINED", libcellml::Issue::ReferenceRule::UNDEFINED)
        .value("DATA_REPR_IDENTIFIER_UNICODE", libcellml::Issue::ReferenceRule::DATA_REPR_IDENTIFIER_UNICODE)
        .value("DATA_REPR_IDENTIFIER_LATIN_ALPHANUM", libcellml::Issue::ReferenceRule::DATA_REPR_IDENTIFIER_LATIN_ALPHANUM)
        .value("DATA_REPR_IDENTIFIER_AT_LEAST_ONE_ALPHANUM", libcellml::Issue::ReferenceRule::DATA_REPR_IDENTIFIER_AT_LEAST_ONE_ALPHANUM)
        .value("DATA_REPR_IDENTIFIER_BEGIN_EURO_NUM", libcellml::Issue::ReferenceRule::DATA_REPR_IDENTIFIER_BEGIN_EURO_NUM)
        .value("DATA_REPR_IDENTIFIER_IDENTICAL", libcellml::Issue::ReferenceRule::DATA_REPR_IDENTIFIER_IDENTICAL)
        .value("DATA_REPR_NNEG_INT_BASE10", libcellml::Issue::ReferenceRule::DATA_REPR_NNEG_INT_BASE10)
        .value("DATA_REPR_NNEG_INT_EURO_NUM", libcellml::Issue::ReferenceRule::DATA_REPR_NNEG_INT_EURO_NUM)
        .value("MODEL_ELEMENT", libcellml::Issue::ReferenceRule::MODEL_ELEMENT)
        .value("MODEL_NAME", libcellml::Issue::ReferenceRule::MODEL_NAME)
        .value("MODEL_CHILD", libcellml::Issue::ReferenceRule::MODEL_CHILD)
        .value("MODEL_MORE_THAN_ONE_ENCAPSULATION", libcellml::Issue::ReferenceRule::MODEL_MORE_THAN_ONE_ENCAPSULATION)
        .value("IMPORT_HREF", libcellml::Issue::ReferenceRule::IMPORT_HREF)
        .value("IMPORT_CHILD", libcellml::Issue::ReferenceRule::IMPORT_CHILD)
        .value("IMPORT_CIRCULAR", libcellml::Issue::ReferenceRule::IMPORT_CIRCULAR)
        .value("IMPORT_UNITS_NAME", libcellml::Issue::ReferenceRule::IMPORT_UNITS_NAME)
        .value("IMPORT_UNITS_REF", libcellml::Issue::ReferenceRule::IMPORT_UNITS_REF)
        .value("IMPORT_COMPONENT_NAME", libcellml::Issue::ReferenceRule::IMPORT_COMPONENT_NAME)
        .value("IMPORT_COMPONENT_REF", libcellml::Issue::ReferenceRule::IMPORT_COMPONENT_REF)
        .value("UNITS_NAME", libcellml::Issue::ReferenceRule::UNITS_NAME)
        .value("UNITS_NAME_UNIQUE", libcellml::Issue::ReferenceRule::UNITS_NAME_UNIQUE)
        .value("UNITS_STANDARD", libcellml::Issue::ReferenceRule::UNITS_STANDARD)
        .value("UNITS_CHILD", libcellml::Issue::ReferenceRule::UNITS_CHILD)
        .value("UNIT_UNITS_REF", libcellml::Issue::ReferenceRule::UNIT_UNITS_REF)
        .value("UNIT_DIGRAPH", libcellml::Issue::ReferenceRule::UNIT_DIGRAPH)
        .value("UNIT_CIRCULAR_REF", libcellml::Issue::ReferenceRule::UNIT_CIRCULAR_REF)
        .value("UNIT_OPTIONAL_ATTRIBUTE", libcellml::Issue::ReferenceRule::UNIT_OPTIONAL_ATTRIBUTE)
        .value("UNIT_PREFIX", libcellml::Issue::ReferenceRule::UNIT_PREFIX)
        .value("UNIT_MULTIPLIER", libcellml::Issue::ReferenceRule::UNIT_MULTIPLIER)
        .value("UNIT_EXPONENT", libcellml::Issue::ReferenceRule::UNIT_EXPONENT)
        .value("COMPONENT_NAME", libcellml::Issue::ReferenceRule::COMPONENT_NAME)
        .value("COMPONENT_CHILD", libcellml::Issue::ReferenceRule::COMPONENT_CHILD)
        .value("VARIABLE_NAME", libcellml::Issue::ReferenceRule::VARIABLE_NAME)
        .value("VARIABLE_UNITS", libcellml::Issue::ReferenceRule::VARIABLE_UNITS)
        .value("VARIABLE_INTERFACE", libcellml::Issue::ReferenceRule::VARIABLE_INTERFACE)
        .value("VARIABLE_INITIAL_VALUE", libcellml::Issue::ReferenceRule::VARIABLE_INITIAL_VALUE)
        .value("RESET_CHILD", libcellml::Issue::ReferenceRule::RESET_CHILD)
        .value("RESET_ORDER", libcellml::Issue::ReferenceRule::RESET_ORDER)
        .value("RESET_VARIABLE_REFERENCE", libcellml::Issue::ReferenceRule::RESET_VARIABLE_REFERENCE)
        .value("RESET_TEST_VARIABLE_REFERENCE", libcellml::Issue::ReferenceRule::RESET_TEST_VARIABLE_REFERENCE)
        .value("RESET_TEST_VALUE", libcellml::Issue::ReferenceRule::RESET_TEST_VALUE)
        .value("RESET_RESET_VALUE", libcellml::Issue::ReferenceRule::RESET_RESET_VALUE)
        .value("MATH_MATHML", libcellml::Issue::ReferenceRule::MATH_MATHML)
        .value("MATH_CHILD", libcellml::Issue::ReferenceRule::MATH_CHILD)
        .value("MATH_CI_VARIABLE_REFERENCE", libcellml::Issue::ReferenceRule::MATH_CI_VARIABLE_REFERENCE)
        .value("MATH_CN_UNITS_ATTRIBUTE", libcellml::Issue::ReferenceRule::MATH_CN_UNITS_ATTRIBUTE)
        .value("ENCAPSULATION_COMPONENT_REF", libcellml::Issue::ReferenceRule::ENCAPSULATION_COMPONENT_REF)
        .value("COMPONENT_REF_COMPONENT_ATTRIBUTE", libcellml::Issue::ReferenceRule::COMPONENT_REF_COMPONENT_ATTRIBUTE)
        .value("COMPONENT_REF_CHILD", libcellml::Issue::ReferenceRule::COMPONENT_REF_CHILD)
        .value("COMPONENT_REF_ENCAPSULATION", libcellml::Issue::ReferenceRule::COMPONENT_REF_ENCAPSULATION)
        .value("CONNECTION_COMPONENT1", libcellml::Issue::ReferenceRule::CONNECTION_COMPONENT1)
        .value("CONNECTION_COMPONENT2", libcellml::Issue::ReferenceRule::CONNECTION_COMPONENT2)
        .value("CONNECTION_UNIQUE_TRANSITIVE", libcellml::Issue::ReferenceRule::CONNECTION_UNIQUE_TRANSITIVE)
        .value("CONNECTION_MAP_VARIABLES", libcellml::Issue::ReferenceRule::CONNECTION_MAP_VARIABLES)
        .value("MAP_VARIABLES_VARIABLE1", libcellml::Issue::ReferenceRule::MAP_VARIABLES_VARIABLE1)
        .value("MAP_VARIABLES_VARIABLE2", libcellml::Issue::ReferenceRule::MAP_VARIABLES_VARIABLE2)
        .value("MAP_VARIABLES_UNIQUE", libcellml::Issue::ReferenceRule::MAP_VARIABLES_UNIQUE)
        .value("MAP_VARIABLES_IDENTICAL_UNIT_REDUCTION", libcellml::Issue::ReferenceRule::MAP_VARIABLES_IDENTICAL_UNIT_REDUCTION)
    ;

    class_<libcellml::Issue>("Issue")
        .smart_ptr_constructor("Issue", select_overload<libcellml::IssuePtr()>(&libcellml::Issue::create))
        .function("description", &libcellml::Issue::description)
        .function("cause", &libcellml::Issue::cause)
        .function("setDescription", &libcellml::Issue::setDescription)
        .function("setCause", &libcellml::Issue::setCause)
        .function("level", &libcellml::Issue::level)
        .function("setLevel", &libcellml::Issue::setLevel)
        .function("referenceRule", &libcellml::Issue::referenceRule)
        .function("setReferenceRule", &libcellml::Issue::setReferenceRule)
        .function("referenceHeading", &libcellml::Issue::referenceHeading)
        .function("component", &libcellml::Issue::component)
        .function("setComponent", &libcellml::Issue::setComponent)
        .function("importSource", &libcellml::Issue::component)
        .function("setImportSource", &libcellml::Issue::setComponent)
        .function("model", &libcellml::Issue::component)
        .function("setModel", &libcellml::Issue::setComponent)
        .function("units", &libcellml::Issue::component)
        .function("setUnits", &libcellml::Issue::setComponent)
        .function("variable", &libcellml::Issue::component)
        .function("setVariable", &libcellml::Issue::setComponent)
        .function("reset", &libcellml::Issue::component)
        .function("setReset", &libcellml::Issue::setComponent)
    ;
}
