# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kmoy001/libCellML

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kmoy001/libCellML

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.14.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kmoy001/libCellML/CMakeFiles /Users/kmoy001/libCellML/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kmoy001/libCellML/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named cellml

# Build rule for target.
cellml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cellml
.PHONY : cellml

# fast build rule for target.
cellml/fast:
	$(MAKE) -f src/CMakeFiles/cellml.dir/build.make src/CMakeFiles/cellml.dir/build
.PHONY : cellml/fast

#=============================================================================
# Target rules for targets named when_swig_compilation

# Build rule for target.
when_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 when_swig_compilation
.PHONY : when_swig_compilation

# fast build rule for target.
when_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/when_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/when_swig_compilation.dir/build
.PHONY : when_swig_compilation/fast

#=============================================================================
# Target rules for targets named python_bindings

# Build rule for target.
python_bindings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 python_bindings
.PHONY : python_bindings

# fast build rule for target.
python_bindings/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/python_bindings.dir/build.make src/bindings/python/CMakeFiles/python_bindings.dir/build
.PHONY : python_bindings/fast

#=============================================================================
# Target rules for targets named when

# Build rule for target.
when: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 when
.PHONY : when

# fast build rule for target.
when/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/when.dir/build.make src/bindings/python/CMakeFiles/when.dir/build
.PHONY : when/fast

#=============================================================================
# Target rules for targets named version_swig_compilation

# Build rule for target.
version_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version_swig_compilation
.PHONY : version_swig_compilation

# fast build rule for target.
version_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/version_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/version_swig_compilation.dir/build
.PHONY : version_swig_compilation/fast

#=============================================================================
# Target rules for targets named variable

# Build rule for target.
variable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 variable
.PHONY : variable

# fast build rule for target.
variable/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/variable.dir/build.make src/bindings/python/CMakeFiles/variable.dir/build
.PHONY : variable/fast

#=============================================================================
# Target rules for targets named validator_swig_compilation

# Build rule for target.
validator_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 validator_swig_compilation
.PHONY : validator_swig_compilation

# fast build rule for target.
validator_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/validator_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/validator_swig_compilation.dir/build
.PHONY : validator_swig_compilation/fast

#=============================================================================
# Target rules for targets named specificationrule_swig_compilation

# Build rule for target.
specificationrule_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 specificationrule_swig_compilation
.PHONY : specificationrule_swig_compilation

# fast build rule for target.
specificationrule_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/specificationrule_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/specificationrule_swig_compilation.dir/build
.PHONY : specificationrule_swig_compilation/fast

#=============================================================================
# Target rules for targets named units_swig_compilation

# Build rule for target.
units_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 units_swig_compilation
.PHONY : units_swig_compilation

# fast build rule for target.
units_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/units_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/units_swig_compilation.dir/build
.PHONY : units_swig_compilation/fast

#=============================================================================
# Target rules for targets named validator

# Build rule for target.
validator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 validator
.PHONY : validator

# fast build rule for target.
validator/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/validator.dir/build.make src/bindings/python/CMakeFiles/validator.dir/build
.PHONY : validator/fast

#=============================================================================
# Target rules for targets named specificationrule

# Build rule for target.
specificationrule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 specificationrule
.PHONY : specificationrule

# fast build rule for target.
specificationrule/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/specificationrule.dir/build.make src/bindings/python/CMakeFiles/specificationrule.dir/build
.PHONY : specificationrule/fast

#=============================================================================
# Target rules for targets named printer

# Build rule for target.
printer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 printer
.PHONY : printer

# fast build rule for target.
printer/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/printer.dir/build.make src/bindings/python/CMakeFiles/printer.dir/build
.PHONY : printer/fast

#=============================================================================
# Target rules for targets named parser_swig_compilation

# Build rule for target.
parser_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser_swig_compilation
.PHONY : parser_swig_compilation

# fast build rule for target.
parser_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/parser_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/parser_swig_compilation.dir/build
.PHONY : parser_swig_compilation/fast

#=============================================================================
# Target rules for targets named namedentity_swig_compilation

# Build rule for target.
namedentity_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 namedentity_swig_compilation
.PHONY : namedentity_swig_compilation

# fast build rule for target.
namedentity_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/namedentity_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/namedentity_swig_compilation.dir/build
.PHONY : namedentity_swig_compilation/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/logger.dir/build.make src/bindings/python/CMakeFiles/logger.dir/build
.PHONY : logger/fast

#=============================================================================
# Target rules for targets named reset

# Build rule for target.
reset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reset
.PHONY : reset

# fast build rule for target.
reset/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/reset.dir/build.make src/bindings/python/CMakeFiles/reset.dir/build
.PHONY : reset/fast

#=============================================================================
# Target rules for targets named model_swig_compilation

# Build rule for target.
model_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 model_swig_compilation
.PHONY : model_swig_compilation

# fast build rule for target.
model_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/model_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/model_swig_compilation.dir/build
.PHONY : model_swig_compilation/fast

#=============================================================================
# Target rules for targets named enumerations

# Build rule for target.
enumerations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enumerations
.PHONY : enumerations

# fast build rule for target.
enumerations/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/enumerations.dir/build.make src/bindings/python/CMakeFiles/enumerations.dir/build
.PHONY : enumerations/fast

#=============================================================================
# Target rules for targets named componententity

# Build rule for target.
componententity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 componententity
.PHONY : componententity

# fast build rule for target.
componententity/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/componententity.dir/build.make src/bindings/python/CMakeFiles/componententity.dir/build
.PHONY : componententity/fast

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/version.dir/build.make src/bindings/python/CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named component_swig_compilation

# Build rule for target.
component_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 component_swig_compilation
.PHONY : component_swig_compilation

# fast build rule for target.
component_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/component_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/component_swig_compilation.dir/build
.PHONY : component_swig_compilation/fast

#=============================================================================
# Target rules for targets named importedentity_swig_compilation

# Build rule for target.
importedentity_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 importedentity_swig_compilation
.PHONY : importedentity_swig_compilation

# fast build rule for target.
importedentity_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/importedentity_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/importedentity_swig_compilation.dir/build
.PHONY : importedentity_swig_compilation/fast

#=============================================================================
# Target rules for targets named printer_swig_compilation

# Build rule for target.
printer_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 printer_swig_compilation
.PHONY : printer_swig_compilation

# fast build rule for target.
printer_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/printer_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/printer_swig_compilation.dir/build
.PHONY : printer_swig_compilation/fast

#=============================================================================
# Target rules for targets named importedentity

# Build rule for target.
importedentity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 importedentity
.PHONY : importedentity

# fast build rule for target.
importedentity/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/importedentity.dir/build.make src/bindings/python/CMakeFiles/importedentity.dir/build
.PHONY : importedentity/fast

#=============================================================================
# Target rules for targets named units

# Build rule for target.
units: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 units
.PHONY : units

# fast build rule for target.
units/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/units.dir/build.make src/bindings/python/CMakeFiles/units.dir/build
.PHONY : units/fast

#=============================================================================
# Target rules for targets named namedentity

# Build rule for target.
namedentity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 namedentity
.PHONY : namedentity

# fast build rule for target.
namedentity/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/namedentity.dir/build.make src/bindings/python/CMakeFiles/namedentity.dir/build
.PHONY : namedentity/fast

#=============================================================================
# Target rules for targets named logger_swig_compilation

# Build rule for target.
logger_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logger_swig_compilation
.PHONY : logger_swig_compilation

# fast build rule for target.
logger_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/logger_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/logger_swig_compilation.dir/build
.PHONY : logger_swig_compilation/fast

#=============================================================================
# Target rules for targets named importsource

# Build rule for target.
importsource: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 importsource
.PHONY : importsource

# fast build rule for target.
importsource/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/importsource.dir/build.make src/bindings/python/CMakeFiles/importsource.dir/build
.PHONY : importsource/fast

#=============================================================================
# Target rules for targets named reset_swig_compilation

# Build rule for target.
reset_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reset_swig_compilation
.PHONY : reset_swig_compilation

# fast build rule for target.
reset_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/reset_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/reset_swig_compilation.dir/build
.PHONY : reset_swig_compilation/fast

#=============================================================================
# Target rules for targets named enumerations_swig_compilation

# Build rule for target.
enumerations_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enumerations_swig_compilation
.PHONY : enumerations_swig_compilation

# fast build rule for target.
enumerations_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/enumerations_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/enumerations_swig_compilation.dir/build
.PHONY : enumerations_swig_compilation/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/parser.dir/build.make src/bindings/python/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named importsource_swig_compilation

# Build rule for target.
importsource_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 importsource_swig_compilation
.PHONY : importsource_swig_compilation

# fast build rule for target.
importsource_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/importsource_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/importsource_swig_compilation.dir/build
.PHONY : importsource_swig_compilation/fast

#=============================================================================
# Target rules for targets named error_swig_compilation

# Build rule for target.
error_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 error_swig_compilation
.PHONY : error_swig_compilation

# fast build rule for target.
error_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/error_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/error_swig_compilation.dir/build
.PHONY : error_swig_compilation/fast

#=============================================================================
# Target rules for targets named entity_swig_compilation

# Build rule for target.
entity_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 entity_swig_compilation
.PHONY : entity_swig_compilation

# fast build rule for target.
entity_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/entity_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/entity_swig_compilation.dir/build
.PHONY : entity_swig_compilation/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/model.dir/build.make src/bindings/python/CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named componententity_swig_compilation

# Build rule for target.
componententity_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 componententity_swig_compilation
.PHONY : componententity_swig_compilation

# fast build rule for target.
componententity_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/componententity_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/componententity_swig_compilation.dir/build
.PHONY : componententity_swig_compilation/fast

#=============================================================================
# Target rules for targets named entity

# Build rule for target.
entity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 entity
.PHONY : entity

# fast build rule for target.
entity/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/entity.dir/build.make src/bindings/python/CMakeFiles/entity.dir/build
.PHONY : entity/fast

#=============================================================================
# Target rules for targets named error

# Build rule for target.
error: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 error
.PHONY : error

# fast build rule for target.
error/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/error.dir/build.make src/bindings/python/CMakeFiles/error.dir/build
.PHONY : error/fast

#=============================================================================
# Target rules for targets named orderedentity_swig_compilation

# Build rule for target.
orderedentity_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orderedentity_swig_compilation
.PHONY : orderedentity_swig_compilation

# fast build rule for target.
orderedentity_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/orderedentity_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/orderedentity_swig_compilation.dir/build
.PHONY : orderedentity_swig_compilation/fast

#=============================================================================
# Target rules for targets named variable_swig_compilation

# Build rule for target.
variable_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 variable_swig_compilation
.PHONY : variable_swig_compilation

# fast build rule for target.
variable_swig_compilation/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/variable_swig_compilation.dir/build.make src/bindings/python/CMakeFiles/variable_swig_compilation.dir/build
.PHONY : variable_swig_compilation/fast

#=============================================================================
# Target rules for targets named orderedentity

# Build rule for target.
orderedentity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orderedentity
.PHONY : orderedentity

# fast build rule for target.
orderedentity/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/orderedentity.dir/build.make src/bindings/python/CMakeFiles/orderedentity.dir/build
.PHONY : orderedentity/fast

#=============================================================================
# Target rules for targets named component

# Build rule for target.
component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 component
.PHONY : component

# fast build rule for target.
component/fast:
	$(MAKE) -f src/bindings/python/CMakeFiles/component.dir/build.make src/bindings/python/CMakeFiles/component.dir/build
.PHONY : component/fast

#=============================================================================
# Target rules for targets named test_model

# Build rule for target.
test_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_model
.PHONY : test_model

# fast build rule for target.
test_model/fast:
	$(MAKE) -f tests/CMakeFiles/test_model.dir/build.make tests/CMakeFiles/test_model.dir/build
.PHONY : test_model/fast

#=============================================================================
# Target rules for targets named clean_coverage

# Build rule for target.
clean_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_coverage
.PHONY : clean_coverage

# fast build rule for target.
clean_coverage/fast:
	$(MAKE) -f tests/CMakeFiles/clean_coverage.dir/build.make tests/CMakeFiles/clean_coverage.dir/build
.PHONY : clean_coverage/fast

#=============================================================================
# Target rules for targets named test_when

# Build rule for target.
test_when: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_when
.PHONY : test_when

# fast build rule for target.
test_when/fast:
	$(MAKE) -f tests/CMakeFiles/test_when.dir/build.make tests/CMakeFiles/test_when.dir/build
.PHONY : test_when/fast

#=============================================================================
# Target rules for targets named test_version

# Build rule for target.
test_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_version
.PHONY : test_version

# fast build rule for target.
test_version/fast:
	$(MAKE) -f tests/CMakeFiles/test_version.dir/build.make tests/CMakeFiles/test_version.dir/build
.PHONY : test_version/fast

#=============================================================================
# Target rules for targets named test_variable

# Build rule for target.
test_variable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_variable
.PHONY : test_variable

# fast build rule for target.
test_variable/fast:
	$(MAKE) -f tests/CMakeFiles/test_variable.dir/build.make tests/CMakeFiles/test_variable.dir/build
.PHONY : test_variable/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) -f tests/CMakeFiles/coverage.dir/build.make tests/CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named test_resolve_imports

# Build rule for target.
test_resolve_imports: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_resolve_imports
.PHONY : test_resolve_imports

# fast build rule for target.
test_resolve_imports/fast:
	$(MAKE) -f tests/CMakeFiles/test_resolve_imports.dir/build.make tests/CMakeFiles/test_resolve_imports.dir/build
.PHONY : test_resolve_imports/fast

#=============================================================================
# Target rules for targets named test_reset

# Build rule for target.
test_reset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_reset
.PHONY : test_reset

# fast build rule for target.
test_reset/fast:
	$(MAKE) -f tests/CMakeFiles/test_reset.dir/build.make tests/CMakeFiles/test_reset.dir/build
.PHONY : test_reset/fast

#=============================================================================
# Target rules for targets named test_validator

# Build rule for target.
test_validator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_validator
.PHONY : test_validator

# fast build rule for target.
test_validator/fast:
	$(MAKE) -f tests/CMakeFiles/test_validator.dir/build.make tests/CMakeFiles/test_validator.dir/build
.PHONY : test_validator/fast

#=============================================================================
# Target rules for targets named test_coverage

# Build rule for target.
test_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_coverage
.PHONY : test_coverage

# fast build rule for target.
test_coverage/fast:
	$(MAKE) -f tests/CMakeFiles/test_coverage.dir/build.make tests/CMakeFiles/test_coverage.dir/build
.PHONY : test_coverage/fast

#=============================================================================
# Target rules for targets named test_printer

# Build rule for target.
test_printer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_printer
.PHONY : test_printer

# fast build rule for target.
test_printer/fast:
	$(MAKE) -f tests/CMakeFiles/test_printer.dir/build.make tests/CMakeFiles/test_printer.dir/build
.PHONY : test_printer/fast

#=============================================================================
# Target rules for targets named test_component

# Build rule for target.
test_component: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_component
.PHONY : test_component

# fast build rule for target.
test_component/fast:
	$(MAKE) -f tests/CMakeFiles/test_component.dir/build.make tests/CMakeFiles/test_component.dir/build
.PHONY : test_component/fast

#=============================================================================
# Target rules for targets named test_parser

# Build rule for target.
test_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_parser
.PHONY : test_parser

# fast build rule for target.
test_parser/fast:
	$(MAKE) -f tests/CMakeFiles/test_parser.dir/build.make tests/CMakeFiles/test_parser.dir/build
.PHONY : test_parser/fast

#=============================================================================
# Target rules for targets named coverage_branches

# Build rule for target.
coverage_branches: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coverage_branches
.PHONY : coverage_branches

# fast build rule for target.
coverage_branches/fast:
	$(MAKE) -f tests/CMakeFiles/coverage_branches.dir/build.make tests/CMakeFiles/coverage_branches.dir/build
.PHONY : coverage_branches/fast

#=============================================================================
# Target rules for targets named test_units

# Build rule for target.
test_units: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_units
.PHONY : test_units

# fast build rule for target.
test_units/fast:
	$(MAKE) -f tests/CMakeFiles/test_units.dir/build.make tests/CMakeFiles/test_units.dir/build
.PHONY : test_units/fast

#=============================================================================
# Target rules for targets named prepare_coverage

# Build rule for target.
prepare_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prepare_coverage
.PHONY : prepare_coverage

# fast build rule for target.
prepare_coverage/fast:
	$(MAKE) -f tests/CMakeFiles/prepare_coverage.dir/build.make tests/CMakeFiles/prepare_coverage.dir/build
.PHONY : prepare_coverage/fast

#=============================================================================
# Target rules for targets named test_error

# Build rule for target.
test_error: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_error
.PHONY : test_error

# fast build rule for target.
test_error/fast:
	$(MAKE) -f tests/CMakeFiles/test_error.dir/build.make tests/CMakeFiles/test_error.dir/build
.PHONY : test_error/fast

#=============================================================================
# Target rules for targets named test_connection

# Build rule for target.
test_connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_connection
.PHONY : test_connection

# fast build rule for target.
test_connection/fast:
	$(MAKE) -f tests/CMakeFiles/test_connection.dir/build.make tests/CMakeFiles/test_connection.dir/build
.PHONY : test_connection/fast

#=============================================================================
# Target rules for targets named test_math

# Build rule for target.
test_math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_math
.PHONY : test_math

# fast build rule for target.
test_math/fast:
	$(MAKE) -f tests/CMakeFiles/test_math.dir/build.make tests/CMakeFiles/test_math.dir/build
.PHONY : test_math/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest_main.dir/build.make tests/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest.dir/build.make tests/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named clean_docs

# Build rule for target.
clean_docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_docs
.PHONY : clean_docs

# fast build rule for target.
clean_docs/fast:
	$(MAKE) -f docs/CMakeFiles/clean_docs.dir/build.make docs/CMakeFiles/clean_docs.dir/build
.PHONY : clean_docs/fast

#=============================================================================
# Target rules for targets named coverage_docs

# Build rule for target.
coverage_docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coverage_docs
.PHONY : coverage_docs

# fast build rule for target.
coverage_docs/fast:
	$(MAKE) -f docs/CMakeFiles/coverage_docs.dir/build.make docs/CMakeFiles/coverage_docs.dir/build
.PHONY : coverage_docs/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f docs/CMakeFiles/docs.dir/build.make docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named api_docs

# Build rule for target.
api_docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 api_docs
.PHONY : api_docs

# fast build rule for target.
api_docs/fast:
	$(MAKE) -f docs/CMakeFiles/api_docs.dir/build.make docs/CMakeFiles/api_docs.dir/build
.PHONY : api_docs/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install"
	@echo "... uninstall"
	@echo "... cellml"
	@echo "... when_swig_compilation"
	@echo "... python_bindings"
	@echo "... when"
	@echo "... version_swig_compilation"
	@echo "... variable"
	@echo "... validator_swig_compilation"
	@echo "... specificationrule_swig_compilation"
	@echo "... units_swig_compilation"
	@echo "... validator"
	@echo "... specificationrule"
	@echo "... printer"
	@echo "... parser_swig_compilation"
	@echo "... namedentity_swig_compilation"
	@echo "... logger"
	@echo "... reset"
	@echo "... model_swig_compilation"
	@echo "... enumerations"
	@echo "... componententity"
	@echo "... version"
	@echo "... component_swig_compilation"
	@echo "... importedentity_swig_compilation"
	@echo "... printer_swig_compilation"
	@echo "... importedentity"
	@echo "... units"
	@echo "... namedentity"
	@echo "... logger_swig_compilation"
	@echo "... importsource"
	@echo "... reset_swig_compilation"
	@echo "... enumerations_swig_compilation"
	@echo "... parser"
	@echo "... importsource_swig_compilation"
	@echo "... error_swig_compilation"
	@echo "... entity_swig_compilation"
	@echo "... model"
	@echo "... componententity_swig_compilation"
	@echo "... entity"
	@echo "... error"
	@echo "... orderedentity_swig_compilation"
	@echo "... variable_swig_compilation"
	@echo "... orderedentity"
	@echo "... component"
	@echo "... test_model"
	@echo "... clean_coverage"
	@echo "... test_when"
	@echo "... test_version"
	@echo "... test_variable"
	@echo "... coverage"
	@echo "... test_resolve_imports"
	@echo "... test_reset"
	@echo "... test_validator"
	@echo "... test_coverage"
	@echo "... test_printer"
	@echo "... test_component"
	@echo "... test_parser"
	@echo "... coverage_branches"
	@echo "... test_units"
	@echo "... prepare_coverage"
	@echo "... test_error"
	@echo "... test_connection"
	@echo "... test_math"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... clean_docs"
	@echo "... coverage_docs"
	@echo "... docs"
	@echo "... api_docs"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

