# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _error
else:
    import _error

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


SpecificationRule_UNDEFINED = _error.SpecificationRule_UNDEFINED
SpecificationRule_DATA_REPR_IDENTIFIER_UNICODE = _error.SpecificationRule_DATA_REPR_IDENTIFIER_UNICODE
SpecificationRule_DATA_REPR_IDENTIFIER_LATIN_ALPHANUM = _error.SpecificationRule_DATA_REPR_IDENTIFIER_LATIN_ALPHANUM
SpecificationRule_DATA_REPR_IDENTIFIER_AT_LEAST_ONE_ALPHANUM = _error.SpecificationRule_DATA_REPR_IDENTIFIER_AT_LEAST_ONE_ALPHANUM
SpecificationRule_DATA_REPR_IDENTIFIER_BEGIN_EURO_NUM = _error.SpecificationRule_DATA_REPR_IDENTIFIER_BEGIN_EURO_NUM
SpecificationRule_DATA_REPR_IDENTIFIER_IDENTICAL = _error.SpecificationRule_DATA_REPR_IDENTIFIER_IDENTICAL
SpecificationRule_DATA_REPR_NNEG_INT_BASE10 = _error.SpecificationRule_DATA_REPR_NNEG_INT_BASE10
SpecificationRule_DATA_REPR_NNEG_INT_EURO_NUM = _error.SpecificationRule_DATA_REPR_NNEG_INT_EURO_NUM
SpecificationRule_MODEL_ELEMENT = _error.SpecificationRule_MODEL_ELEMENT
SpecificationRule_MODEL_NAME = _error.SpecificationRule_MODEL_NAME
SpecificationRule_MODEL_CHILD = _error.SpecificationRule_MODEL_CHILD
SpecificationRule_MODEL_MORE_THAN_ONE_ENCAPSULATION = _error.SpecificationRule_MODEL_MORE_THAN_ONE_ENCAPSULATION
SpecificationRule_IMPORT_HREF = _error.SpecificationRule_IMPORT_HREF
SpecificationRule_IMPORT_CHILD = _error.SpecificationRule_IMPORT_CHILD
SpecificationRule_IMPORT_CIRCULAR = _error.SpecificationRule_IMPORT_CIRCULAR
SpecificationRule_IMPORT_UNITS_NAME = _error.SpecificationRule_IMPORT_UNITS_NAME
SpecificationRule_IMPORT_UNITS_REF = _error.SpecificationRule_IMPORT_UNITS_REF
SpecificationRule_IMPORT_COMPONENT_NAME = _error.SpecificationRule_IMPORT_COMPONENT_NAME
SpecificationRule_IMPORT_COMPONENT_REF = _error.SpecificationRule_IMPORT_COMPONENT_REF
SpecificationRule_UNITS_NAME = _error.SpecificationRule_UNITS_NAME
SpecificationRule_UNITS_NAME_UNIQUE = _error.SpecificationRule_UNITS_NAME_UNIQUE
SpecificationRule_UNITS_STANDARD = _error.SpecificationRule_UNITS_STANDARD
SpecificationRule_UNITS_CHILD = _error.SpecificationRule_UNITS_CHILD
SpecificationRule_UNIT_UNITS_REF = _error.SpecificationRule_UNIT_UNITS_REF
SpecificationRule_UNIT_DIGRAPH = _error.SpecificationRule_UNIT_DIGRAPH
SpecificationRule_UNIT_CIRCULAR_REF = _error.SpecificationRule_UNIT_CIRCULAR_REF
SpecificationRule_UNIT_OPTIONAL_ATTRIBUTE = _error.SpecificationRule_UNIT_OPTIONAL_ATTRIBUTE
SpecificationRule_UNIT_PREFIX = _error.SpecificationRule_UNIT_PREFIX
SpecificationRule_UNIT_MULTIPLIER = _error.SpecificationRule_UNIT_MULTIPLIER
SpecificationRule_UNIT_EXPONENT = _error.SpecificationRule_UNIT_EXPONENT
SpecificationRule_COMPONENT_NAME = _error.SpecificationRule_COMPONENT_NAME
SpecificationRule_COMPONENT_CHILD = _error.SpecificationRule_COMPONENT_CHILD
SpecificationRule_VARIABLE_NAME = _error.SpecificationRule_VARIABLE_NAME
SpecificationRule_VARIABLE_UNITS = _error.SpecificationRule_VARIABLE_UNITS
SpecificationRule_VARIABLE_INTERFACE = _error.SpecificationRule_VARIABLE_INTERFACE
SpecificationRule_VARIABLE_INITIAL_VALUE = _error.SpecificationRule_VARIABLE_INITIAL_VALUE
SpecificationRule_RESET_CHILD = _error.SpecificationRule_RESET_CHILD
SpecificationRule_RESET_ORDER = _error.SpecificationRule_RESET_ORDER
SpecificationRule_RESET_VARIABLE_REFERENCE = _error.SpecificationRule_RESET_VARIABLE_REFERENCE
SpecificationRule_WHEN_ORDER = _error.SpecificationRule_WHEN_ORDER
SpecificationRule_WHEN_CHILD = _error.SpecificationRule_WHEN_CHILD
SpecificationRule_MATH_MATHML = _error.SpecificationRule_MATH_MATHML
SpecificationRule_MATH_CHILD = _error.SpecificationRule_MATH_CHILD
SpecificationRule_MATH_CI_VARIABLE_REFERENCE = _error.SpecificationRule_MATH_CI_VARIABLE_REFERENCE
SpecificationRule_MATH_CN_UNITS_ATTRIBUTE = _error.SpecificationRule_MATH_CN_UNITS_ATTRIBUTE
SpecificationRule_ENCAPSULATION_COMPONENT_REF = _error.SpecificationRule_ENCAPSULATION_COMPONENT_REF
SpecificationRule_COMPONENT_REF_COMPONENT_ATTRIBUTE = _error.SpecificationRule_COMPONENT_REF_COMPONENT_ATTRIBUTE
SpecificationRule_COMPONENT_REF_CHILD = _error.SpecificationRule_COMPONENT_REF_CHILD
SpecificationRule_COMPONENT_REF_ENCAPSULATION = _error.SpecificationRule_COMPONENT_REF_ENCAPSULATION
SpecificationRule_CONNECTION_COMPONENT1 = _error.SpecificationRule_CONNECTION_COMPONENT1
SpecificationRule_CONNECTION_COMPONENT2 = _error.SpecificationRule_CONNECTION_COMPONENT2
SpecificationRule_CONNECTION_UNIQUE_TRANSITIVE = _error.SpecificationRule_CONNECTION_UNIQUE_TRANSITIVE
SpecificationRule_CONNECTION_MAP_VARIABLES = _error.SpecificationRule_CONNECTION_MAP_VARIABLES
SpecificationRule_MAP_VARIABLES_VARIABLE1 = _error.SpecificationRule_MAP_VARIABLES_VARIABLE1
SpecificationRule_MAP_VARIABLES_VARIABLE2 = _error.SpecificationRule_MAP_VARIABLES_VARIABLE2
SpecificationRule_MAP_VARIABLES_UNIQUE = _error.SpecificationRule_MAP_VARIABLES_UNIQUE
class Error(object):
    r"""Base class for errors used with logger derived classes."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    __swig_destroy__ = _error.delete_Error

    def __init__(self, *args):
        _error.Error_swiginit(self, _error.new_Error(*args))
    Kind_COMPONENT = _error.Error_Kind_COMPONENT
    Kind_CONNECTION = _error.Error_Kind_CONNECTION
    Kind_ENCAPSULATION = _error.Error_Kind_ENCAPSULATION
    Kind_IMPORT = _error.Error_Kind_IMPORT
    Kind_MATHML = _error.Error_Kind_MATHML
    Kind_MODEL = _error.Error_Kind_MODEL
    Kind_RESET = _error.Error_Kind_RESET
    Kind_UNDEFINED = _error.Error_Kind_UNDEFINED
    Kind_UNITS = _error.Error_Kind_UNITS
    Kind_VARIABLE = _error.Error_Kind_VARIABLE
    Kind_WHEN = _error.Error_Kind_WHEN
    Kind_XML = _error.Error_Kind_XML

    def setDescription(self, description):
        r"""Sets a string description for why this error was raised."""
        return _error.Error_setDescription(self, description)

    def getDescription(self):
        r"""Get a string description for why this error was raised."""
        return _error.Error_getDescription(self)

    def setKind(self, kind):
        r"""Sets the ``kind`` of this error."""
        return _error.Error_setKind(self, kind)

    def getKind(self):
        r"""
        Get the ``kind`` of this error. If no kind has been set for this error, will
        return Kind::UNDEFINED.
        """
        return _error.Error_getKind(self)

    def isKind(self, kind):
        r"""Tests if this error matches the given ``kind``."""
        return _error.Error_isKind(self, kind)

    def setRule(self, rule):
        r"""Sets the :class:`SpecificationRule` for this error."""
        return _error.Error_setRule(self, rule)

    def getRule(self):
        r"""Get the :class:`SpecificationRule` of this error."""
        return _error.Error_getRule(self)

    def getSpecificationHeading(self):
        r"""
        Returns the CellML 2.0 Specification heading associated with the
        :class:`SpecificationRule` for this error (empty string if not set).
        """
        return _error.Error_getSpecificationHeading(self)

    def setComponent(self, component):
        r"""Sets the :class:`Component` that this error is relevant to (``None`` to unset)."""
        return _error.Error_setComponent(self, component)

    def getComponent(self):
        r"""Returns the :class:`Component` that this error is relevant to (or ``None``)."""
        return _error.Error_getComponent(self)

    def setImportSource(self, importSource):
        r"""Sets the :class:`ImportSource` that this error is relevant to (``None`` to unset)."""
        return _error.Error_setImportSource(self, importSource)

    def getImportSource(self):
        r"""Returns the :class:`ImportSource` that this error is relevant to (or ``None``)."""
        return _error.Error_getImportSource(self)

    def setModel(self, model):
        r"""Sets the :class:`Model` that this error is relevant to (``None`` to unset)."""
        return _error.Error_setModel(self, model)

    def getModel(self):
        r"""Returns the :class:`Model` that this error is relevant to (or ``None``)."""
        return _error.Error_getModel(self)

    def setUnits(self, units):
        r"""Sets the :class`Units` that this error is relevant to (``None`` to unset)."""
        return _error.Error_setUnits(self, units)

    def getUnits(self):
        r"""Get the :class:`Units` that this error is relevant to (or ``None``)."""
        return _error.Error_getUnits(self)

    def setVariable(self, variable):
        r"""Sets the :class:`Variable` that this error is relevant to (``None`` to unset)."""
        return _error.Error_setVariable(self, variable)

    def getVariable(self):
        r"""Get the :class:`Variable` that this error is relevant to (or ``None``)."""
        return _error.Error_getVariable(self)

    def setReset(self, reset):
        r"""Sets the :class:`Reset` that this error is relevant to (``None`` to unset)."""
        return _error.Error_setReset(self, reset)

    def getReset(self):
        r"""Get the :class:`Reset` that this error is relevant to (or ``None``)."""
        return _error.Error_getReset(self)

    def setWhen(self, when):
        r"""Sets the :class:`When` that this error is relevant to (``None`` to unset)."""
        return _error.Error_setWhen(self, when)

    def getWhen(self):
        r"""Get the :class:`When` that this error is relevant to (or ``None``)."""
        return _error.Error_getWhen(self)

# Register Error in _error:
_error.Error_swigregister(Error)



