# CMake generated Testfile for 
# Source directory: /Users/kmoy001/libCellML/tests
# Build directory: /Users/kmoy001/libCellML/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(entities_unit_test_component "/Users/kmoy001/libCellML/tests/test_component")
set_tests_properties(entities_unit_test_component PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(entities_unit_test_connection "/Users/kmoy001/libCellML/tests/test_connection")
set_tests_properties(entities_unit_test_connection PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(misc_unit_test_coverage "/Users/kmoy001/libCellML/tests/test_coverage")
set_tests_properties(misc_unit_test_coverage PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(object_unit_test_error "/Users/kmoy001/libCellML/tests/test_error")
set_tests_properties(object_unit_test_error PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(entities_unit_test_math "/Users/kmoy001/libCellML/tests/test_math")
set_tests_properties(entities_unit_test_math PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(entities_unit_test_model "/Users/kmoy001/libCellML/tests/test_model")
set_tests_properties(entities_unit_test_model PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(io_unit_test_parser "/Users/kmoy001/libCellML/tests/test_parser")
set_tests_properties(io_unit_test_parser PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(io_unit_test_printer "/Users/kmoy001/libCellML/tests/test_printer")
set_tests_properties(io_unit_test_printer PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(entities_unit_test_reset "/Users/kmoy001/libCellML/tests/test_reset")
set_tests_properties(entities_unit_test_reset PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(io_unit_test_resolve_imports "/Users/kmoy001/libCellML/tests/test_resolve_imports")
set_tests_properties(io_unit_test_resolve_imports PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(entities_unit_test_units "/Users/kmoy001/libCellML/tests/test_units")
set_tests_properties(entities_unit_test_units PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(io_unit_test_validator "/Users/kmoy001/libCellML/tests/test_validator")
set_tests_properties(io_unit_test_validator PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(entities_unit_test_variable "/Users/kmoy001/libCellML/tests/test_variable")
set_tests_properties(entities_unit_test_variable PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(api_unit_test_version "/Users/kmoy001/libCellML/tests/test_version")
set_tests_properties(api_unit_test_version PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
add_test(entities_unit_test_when "/Users/kmoy001/libCellML/tests/test_when")
set_tests_properties(entities_unit_test_when PROPERTIES  _BACKTRACE_TRIPLES "/Users/kmoy001/libCellML/tests/CMakeLists.txt;61;add_test;/Users/kmoy001/libCellML/tests/CMakeLists.txt;0;")
subdirs("gtest")
subdirs("bindings")
