/*
Copyright libCellML Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

#pragma once

#include <string>

namespace libcellml {

/**
 * The content of this file is generated, do not edit this file directly.
 * See docs/dev_utilities.rst for further information.
 */
static const char C_GENERATOR_PROFILE_SHA1[] = "47a9b5b8e33ce2fa29c0385e0debe1d295a7e313";
static const char PYTHON_GENERATOR_PROFILE_SHA1[] = "f171d1553ad485ad286b4a1152bc7d89631750a6";

} // namespace libcellml
