name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Base branch (main or tag)"
        default: 'main'
        required: true
      version:
        description: "Release version (e.g. 0.7.1, 0.7.0-post.1)"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest

    env:
      BRANCH_PREFIX: release-staging-v

    steps:
      - uses: actions/checkout@v6
        with:
          ref: release
          path: release-repo

      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.source_branch }}
          path: source-repo

      - name: Create staging branch
        run: |
          cd release-repo
          git checkout -b ${{ env.BRANCH_PREFIX }}${{ inputs.version }}

      - name: Update version numbers
        run: |
          cd source-repo

          version=${{ inputs.version }}
          core=$(sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+).*/\1/' <<< "$version")
          dev="${version#"$core"}"
          echo "Core version: $core, Dev suffix: $dev"
          python3 .github/scripts/set_version.py . $core $dev

      - name: Copy changes to release repo
        run: |
          rsync -av --exclude='.git' source-repo/ release-repo/

      - name: Commit version bump
        run: |
          cd release-repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Prepare release v${{ inputs.version }}"

      - name: Push branch
        run: |
          cd release-repo
          git push origin ${{ env.BRANCH_PREFIX }}${{ inputs.version }}

      - name: Open PR
        uses: peter-evans/create-pull-request@v8
        with:
          base: release
          branch: ${{ env.BRANCH_PREFIX }}${{ inputs.version }}
          title: "Proposed release changes for v${{ inputs.version }}"
          draft: true
          body: |
            Automated release PR for v${{ inputs.version }}
            **Do not** merge this PR, it is only for review and testing. The release process will deal with it when the release is finalised.
