name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Base branch (main or tag)"
        default: 'main'
        required: true
      version:
        description: "Release version (e.g. 0.7.1, 0.7.0-rc.1)"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest

    env:
      BRANCH_PREFIX: release-staging-v

    steps:
      - uses: actions/checkout@v6
        with:
          ref: release
          path: release-repo

      - name: Set GitHub Actions bot identity
        run: |
          cd release-repo

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.source_branch }}
          path: source-repo

      - name: Create staging branch
        run: |
          cd release-repo
          git checkout -b ${{ vars.RELEASE_STAGING_BRANCH_STEM }}${{ inputs.version }}

      - name: Copy release changes to release repo
        run: |
          rsync -avW --delete --exclude='.git' source-repo/ release-repo/

      - name: Commit changes
        run: |
          cd release-repo

          git add -A
          git commit -m "Changes to update the codebase to release v${{ inputs.version }}."

      - name: Push branch
        run: |
          echo "_------------_"
          ls -l release-repo
          echo "_------------_"
          ls -l release-repo/.github
          echo "_------------_"
          ls -l release-repo/.github/workflows
          echo "_------------_"
          cd release-repo
          git push origin ${{ vars.RELEASE_STAGING_BRANCH_STEM }}${{ inputs.version }}

      - name: Generate and commit changelog
        uses: ./release-repo/.github/workflows/release-changelog.yml
        with:
          changelog_branch: ${{ vars.RELEASE_STAGING_BRANCH_STEM }}${{ inputs.version }}

      - name: Set version
        uses: ./release-repo/.github/workflows/set-version.yml
        with:
          target_branch: ${{ vars.RELEASE_STAGING_BRANCH_STEM }}${{ inputs.version }}
          version: ${{ inputs.version }}

      - name: Open PR
        id: open_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Automated release PR for v${{ inputs.version }}." > pr_body.txt
          echo "" >> pr_body.txt
          echo "**Do not** merge this PR, it is only for review and testing." >> pr_body.txt
          echo "The release process will deal with it when the release is finalised." >> pr_body.txt

          cd release-repo
          gh pr create \
            --base release \
            --head ${{ vars.RELEASE_STAGING_BRANCH_STEM }}${{ inputs.version }} \
            --title "Proposed changes to create release v${{ inputs.version }} of libCellML" \
            --body-file ../pr_body.txt \
            --draft        

      - name: Delete remote branch if PR creation failed
        if: failure() && steps.open_pr.outcome == 'failure'
        run: |
          cd release-repo
          git push origin --delete ${{ vars.RELEASE_STAGING_BRANCH_STEM }}${{ inputs.version }}
